/*
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import * as path from 'path';
import {
  Aws, CustomResource, Duration,
  RemovalPolicy,
} from 'aws-cdk-lib';
import {
  Code, Function,
  LayerVersion,
  Runtime,
} from 'aws-cdk-lib/aws-lambda';
import { PolicyStatement, Effect, Role, ServicePrincipal, Policy } from 'aws-cdk-lib/aws-iam';
import { Provider } from 'aws-cdk-lib/custom-resources';
import { Construct } from 'constructs';
import { SolutionInfo } from '../common/solution-info';

export interface DeleteAgentResourcesProps {
  readonly adminAccountId: string;
}

// delete agent resources generated by the program
export class DeleteAgentResourcesStack extends Construct {
  constructor(scope: Construct, id: string, props: DeleteAgentResourcesProps) {
    super(scope, id);

    // Create a lambda layer with required python packages.
    const deleteAgentResourcesLayer = new LayerVersion(this, 'DeleteAgentResources', {
      code: Code.fromAsset(path.join(__dirname, './delete-agent-resources'), {
        bundling: {
          image: Runtime.PYTHON_3_9.bundlingImage,
          command: [
            'bash',
            '-c',
            `pip install -r requirements.txt ${SolutionInfo.PIP_MIRROR_PARAMETER} -t /asset-output/python`,
          ],
        },
      }),
      layerVersionName: `${SolutionInfo.SOLUTION_NAME_ABBR}-DeleteAgentResources`,
      compatibleRuntimes: [Runtime.PYTHON_3_9],
      description: `${SolutionInfo.SOLUTION_NAME} - delete resources generated by the program layer`,
    });

    const deleteAgentResourcesRole = new Role(this, 'DeleteAgentResourcesRole', {
      assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
    });
    deleteAgentResourcesRole.attachInlinePolicy(new Policy(this, 'DeleteAgentResourcePolicy', {
      policyName: 'DeleteAgentResourcePolicy',
      statements: [
        new PolicyStatement({
          effect: Effect.ALLOW,
          actions: [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
            "glue:GetDatabase",
            "glue:GetDatabases",
            "glue:DeleteDatabase",
            "glue:GetConnections",
            "glue:DeleteConnection",
            "glue:GetTable",
            "glue:GetTables",
            "glue:DeleteTable",
            "glue:GetCrawler",
            "glue:ListCrawlers",
            "glue:DeleteCrawler",
            "glue:ListJobs",
            "glue:DeleteJob",
          ],
          resources: ["*"]
        }),
      ]
    }));

    const deleteAgentResourcesFunction = new Function(this, 'DeleteAgentResourcesFunction', {
      functionName: `${SolutionInfo.SOLUTION_NAME_ABBR}-DeleteAgentResources`,
      description: `${SolutionInfo.SOLUTION_NAME} - delete resources generated by the agent program`,
      runtime: Runtime.PYTHON_3_9,
      handler: 'delete_agent_resources.lambda_handler',
      code: Code.fromAsset(path.join(__dirname, './delete-agent-resources')),
      timeout: Duration.minutes(15),
      layers: [deleteAgentResourcesLayer],
      role: deleteAgentResourcesRole,
      environment: { "AdminAccountId": props.adminAccountId },
    });
    deleteAgentResourcesFunction.node.addDependency(deleteAgentResourcesRole);

    const deleteAgentResourcesProvider = new Provider(this, 'DeleteAgentResourcesProvider', {
      onEventHandler: deleteAgentResourcesFunction,
    });

    const deleteAgentResourcesTrigger = new CustomResource(this, 'DeleteAgentResourcesTrigger', {
      serviceToken: deleteAgentResourcesProvider.serviceToken,
      properties: {
        SolutionNameAbbr: SolutionInfo.SOLUTION_NAME_ABBR,
      },
    });
    deleteAgentResourcesTrigger.node.addDependency(deleteAgentResourcesProvider);
  }
}
